# Generated by Django 5.2.8 on 2025-11-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='callback_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='callback_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_desc',
            field=models.TextField(blank=True),
        ),
    ]
