# Generated by Django 5.2.8 on 2025-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='category',
            field=models.CharField(choices=[('free', 'Free'), ('regular', 'Regular'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='regular', max_length=10),
        ),
    ]
